version: '3.3'
services:
  wiki:
    networks:
      - proxy
    image: sc-registry.fredhutch.org/wiki-preview:latest
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sciwiki-preview.rule=Host(`sciwiki-preview.fredhutch.org`)"
        - "traefik.http.routers.sciwiki-preview-secured.rule=Host(`sciwiki-preview.fredhutch.org`)"
        - "traefik.http.routers.sciwiki-preview.entrypoints=web,web-secured"
        - "traefik.http.services.sciwiki-preview.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.sciwiki-preview.tls=true"


networks:
  proxy:
    external: true
